#!/bin/bash

NETWORK=vizix-network

# delete network if exists
if ! [[ -z `docker network ls | grep $NETWORK` ]]; then
  docker network rm $NETWORK
fi

# create network
docker network create -d bridge $NETWORK
