#!/bin/bash
echo
echo "### stopping/removing bridge"
echo
docker stop MnSFTPitem
docker rm -f MnSFTPitem

echo
echo "### running bridge"
echo
docker run -d --name MnSFTPitem -h MnSFTPitem \
--link mysql \
--link mosquitto \
--link hazelcast1 \
--link hazelcast2 \
-e VIZIX_BRIDGE_TYPE=ftpbridge \
-e VIZIX_FTPB_CODE=MnSFTPitem \
-e VIZIX_HAZELCAST_NATIVE_CLIENT_ADDRESS=hazelcast1 \
vizix-bridges
