#!/bin/bash
echo
echo "### stopping/removing hazelcast nodes"
echo
docker stop hazelcast1
docker stop hazelcast2
docker rm -f hazelcast1
docker rm -f hazelcast2

echo
echo "### running hazelcast nodes"
echo
docker run -d --name hazelcast1 -h hazelcast1 \
--network vizix-network \
-p 5701:5701 \
-e VIZIX_HAZELCAST_MEMBER_LIST=hazelcast1,hazelcast2 \
-e VIZIX_HAZELCAST_PUBLIC_ADDRESS=hazelcast1 \
mojix/hazelcast

docker run -d --name hazelcast2 -h hazelcast2 \
--network vizix-network \
-p 5702:5701 \
-e VIZIX_HAZELCAST_MEMBER_LIST=hazelcast1,hazelcast2 \
-e VIZIX_HAZELCAST_PUBLIC_ADDRESS=hazelcast2 \
mojix/hazelcast
