#!/bin/bash
echo
echo "### stopping/removing services"
echo
docker stop corebridge
docker rm -f corebridge

echo
echo "### running services"
echo
docker run -d --name corebridge -h corebridge \
--link mongo \
--link mysql \
--link mosquitto \
--link hazelcast1 \
--link hazelcast2 \
--link services \
--link services:backend \
-e VIZIX_API_HOST=backend \
-e VIZIX_BRIDGE_TYPE=corebridgemt \
-e VIZIX_CORE_CODE=CBDerby \
-e VIZIX_CORE_LAZY_LOAD=true \
-e VIZIX_HAZELCAST_NATIVE_CLIENT_ADDRESS=hazelcast1 \
-e VIZIX_API_KEY=7007BD9D \
vizix-bridges
