#!/bin/bash
echo
echo "### stopping/removing services"
echo
docker stop backend
docker rm -f backend

echo
echo "### running services"
echo
docker run -d --name backend -h backend \
--network vizix-network \
-p 8080:8080 \
-e VIZIX_MONGO_HOST=mongo \
-e VIZIX_MQTT_HOST=mosquitto \
-e VIZIX_MYSQL_HOST=mysql \
-e VIZIX_MYSQL_PASSWORD=control123! \
-e VIZIX_HAZELCAST_DISTRIBUTED_ENABLE=true \
-e VIZIX_HAZELCAST_NATIVE_CLIENT_ADDRESS=hazelcast1 \
vizix-services
