#!/bin/bash
echo
echo "### stopping/removing alebridge"
echo
docker stop alebridge
docker rm -f alebridge

echo
echo "### running alebridge"
echo
docker run -d --name alebridge -h alebridge \
-p 9090:9090 \
--network vizix-network \
-e VIZIX_BRIDGE_TYPE=alebridgemt \
-e VIZIX_ALEB_CODE=ALEB \
-e VIZIX_HAZELCAST_NATIVE_CLIENT_ADDRESS=hazelcast2 \
vizix-bridges
