#!/bin/bash
echo
echo "### stopping/removing ui"
echo
docker stop ui
docker rm -f ui

echo
echo "### running ui"
echo
docker run -d --name ui -h ui \
--network vizix-network \
-p 80:80 -e VIZIX_API_HOST=localhost:8080 \
ui
